name = "fileshare"
main = "./src/index.js"
compatibility_date = "2022-11-08"

kv_namespaces = [
  { binding = "dingding", id = "e0612a289cdb409b955eb345959be201",preview_id='e0612a289cdb409b955eb345959be201'}
]
[site]
bucket = "./static/dist"
